version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: ./watchmedo.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      DJANGO_ALLOWED_HOSTS: "localhost"
      POSTGRES_DB: neonpg_db_name # Replace with your actual DB name
      POSTGRES_USER: neonpg_user # Replace with your actual DB user
      POSTGRES_PASSWORD: neonpg_password # Replace with your actual DB password
      POSTGRES_HOST: neonpg_host # Replace with your actual DB host
      POSTGRES_PORT: neonpg_port # Replace with your actual DB port

volumes:
  postgres_data:
